### ISSUE TITLE
执行main.py 报错：ValueError: check_hostname requires server_hostname

### ISSUE THREAD

**Issue by zzZfans** [Sniper970119/dianping_spider#10]
执行main.py 报错：ValueError: check_hostname requires server_hostname

**Comment by Sniper970119** [comment]
选择了mongo存储方式但是没配置（对）mongo路径

**Comment by zzZfans** [comment]
> 选择了mongo存储方式但是没配置（对）mongo路径

改选了csv但没有管mongo路径

**Comment by Sniper970119** [comment]
![图片](https://user-images.githubusercontent.com/30463691/114270813-f988ab00-9a40-11eb-8b3b-9c4748502568.png)

**Comment by zzZfans** [comment]
> ![图片](https://user-images.githubusercontent.com/30463691/114270813-f988ab00-9a40-11eb-8b3b-9c4748502568.png)
> 
> 

好的

**Comment by zzZfans** [comment]
pip install urllib3==1.25.7 解决问题
