### ISSUE TITLE
random.shuffle 错误

### ISSUE THREAD

**Issue by ParaNoth** [Sniper970119/dianping_spider#11]
感谢作者的作品。使用的时候发现一个BUG：
`utils/cookie_utils.py`  第117行:
```python
self.all_cookie=random.shuffle(self.all_cookie)
```
random.shuffle直接打乱传入的列表，返回会返回一个None，会把self.all_cookie变为None导致下方代码出错。

**Comment by Sniper970119** [comment]
更新了
