### ISSUE TITLE
您好，我的一直卡在这里，是为啥呢？我用了代理，但是还是被大众点评拒绝访问了

### ISSUE THREAD

**Issue by dingrutao32** [Sniper970119/dianping_spider#16]
![image](https://user-images.githubusercontent.com/38903865/119096443-308dab80-ba46-11eb-8f6e-ad8b3406cc55.png)

**Comment by dingrutao32** [comment]
我想爬取的是数据是，比如一列门店的名字，我搜索门店，获取这些门店的人均消费及门店种类就行了，但是您这个好像只支持一个大类的搜索吗？

**Comment by Sniper970119** [comment]
你好，看了你提的issue并没办法准确判断是什么问题。
如果等待很久（30秒）以上依然没有报错（用来排除低质量代理造成的响应过慢），可能就是配置项有一些问题。

可以提供一下配置文件参数吗

**Comment by dingrutao32** [comment]
![image](https://user-images.githubusercontent.com/38903865/119286737-a462ca80-bc77-11eb-9d2b-6ad86e477632.png)
您好，配置如图，
![image](https://user-images.githubusercontent.com/38903865/119286883-ebe95680-bc77-11eb-9113-7c984cafa71a.png)
我需要的结果是这边有一个清单，可能几百家的店铺名称，然后我需要获取这两个字段，这个需要咋操作？

**Comment by Sniper970119** [comment]
1.有可能是代理质量不过关。
2.对于搜索任务，ip代理带来的性能提升是不确定的（也就是不确定是正向还是反向优化）。
    ip代理只在匿名接口模式下（need_detail=False）有明显的性能提升。
3. require,ini 中的所有项可以配置成=False
4. save_mode 应该为mongo 而不是mongodb（这里文档有错误引导，之后会改正）
5. 我不是很确定你的mongodb://hadoop011:27017是否为合法地址。一般应该为 mongodb://127.0.0.1:27017或者一个完整的域名。
6. 对于几百家店铺的搜索，需要自行编写代码调用function.search中的search方法

**Comment by dingrutao32** [comment]
好的，代理质量确实不好，用的网上公共代理池。
我尝试下您给的方案。
十分感谢！

**Comment by Sniper970119** [comment]
如果没问题了记得回来给issue关掉，我就不关了。
