### ISSUE TITLE
请教下复现时几个问题

### ISSUE THREAD

**Issue by DOO715** [Sniper970119/dianping_spider#17]
主要是复现是卡在了这步
![image](https://user-images.githubusercontent.com/51997734/119846744-fc7e2300-bf3c-11eb-8530-13ee20e651f8.png)

想请教下config.ini设置有没有问题

1、没有找到tcv 和uuid，使用的是默认值
主要是抓包的时候没有找到相应的allReview或者basicHiddenInfo的请求连接

2、mongdb设置为：mongo_path = mongodb://127.0.0.1:27017
运行时启动了mongod，能正常打开127.0.0.1:27017，如下图所示
![image](https://user-images.githubusercontent.com/51997734/119847197-5b439c80-bf3d-11eb-9d7f-4a88d9d8c365.png)

但是是初次使用，不确定mongdb是否设置成功？
另外商家搜索结果展示的图，请问是用什么软件看的？
![image](https://user-images.githubusercontent.com/51997734/119847336-79a99800-bf3d-11eb-9180-b2fcd6c09285.png)

3、keyword默认写的火锅，请问可以置空值吗？

**Comment by Sniper970119** [comment]
1. require.ini 中 谨慎值为True可以不用tsv和uuid，否则需要更新。
2. 正确，Navicat或者其他 数据库可视化 软件
3. 不可以（但是在使用定制url模式时会失效，但并不代表可以删）

**Comment by DOO715** [comment]
http提取接口需要设置吗？
无论此项删掉与否，这个配置下依然没速度呢
![image](https://user-images.githubusercontent.com/51997734/119854819-f8a1cf00-bf43-11eb-89c4-b8a52a10d257.png)
![image](https://user-images.githubusercontent.com/51997734/119855109-3a327a00-bf44-11eb-822d-360130a5e26d.png)

**Comment by Sniper970119** [comment]
如果use_proxy 为 True  则至少需要http_link 或者 key_id key_key（没有开发）中的一项。

也就是目前为止，必须要http_link ，详情查看 docs里的proxy.md

**Comment by Sniper970119** [comment]
如果没问题了 就把issue关了吧
