### ISSUE TITLE
现在还能爬吗？

### ISSUE THREAD

**Issue by decenttech** [Sniper970119/dianping_spider#18]
搜索页数:   0%|          | 0/5 [00:00<?, ?it/s]
详细爬取:   0%|          | 0/15 [00:00<?, ?it/s]2021-05-28 14:26:17,472 - 4692-MainThread - G:\D11\dianping_spider\function\get_encryption_requests.py[line:108] - WARNING: 代理质量较低
详细爬取:   0%|          | 0/15 [00:00<?, ?it/s]
搜索页数:   0%|          | 0/5 [00:01<?, ?it/s]

感觉配置成功了，但是提示这个

**Comment by Sniper970119** [comment]
https://github.com/Sniper970119/dianping_spider/blob/master/docs/problems.md#6warning-%E6%9B%BF%E6%8D%A2tsv%E5%92%8Cuuid%E6%88%96%E8%80%85%E4%BB%A3%E7%90%86%E8%B4%A8%E9%87%8F%E8%BE%83%E4%BD%8E

为什么不看全呢？

https://github.com/Sniper970119/dianping_spider/blob/master/docs/problems.md#%E5%86%99%E5%9C%A8%E6%9C%80%E5%90%8E
