### ISSUE TITLE
请问前辈，cookie很快失效，用selenium会不会好点呢?

### ISSUE THREAD

**Issue by ninghongbo123** [Sniper970119/dianping_spider#19]
anthor question:  do you have review data?  if so , i can contact you.

**Comment by Sniper970119** [comment]
不会，cookie失效意味着你浏览器打开大众点评登录状态也不在。

**Comment by ninghongbo123** [comment]
哦哦，谢谢回复。
我想问的是，用selenium是不是比request要好点呢？
如果在请求网页的过程中，采用打乱顺序请求的方式，会不会比顺序请求的流量更不容易反爬呢？

**Comment by Sniper970119** [comment]
1.selenium慢。而且selenium更容易被检测，而且从最终的请求结果来看，二者一样。而且大众点评（美团）的验证码机制也是json发送验证码链接，携带verify_id，验证通过后服务器对verify_id解除限制（而不是在页面中动态加载）。因此浏览器端并没有什么显著的优势。
2.恰恰相反。如果你有系统的看过我的文档，你就会知道很多时候要处理冷启动请求问题。乱序请求恰恰加剧了冷启动问题。
