### ISSUE TITLE
请问可以爬取图片吗

### ISSUE THREAD

**Issue by 121786404** [Sniper970119/dianping_spider#2]

**Comment by Sniper970119** [comment]
暂时不可以，但是搜索页显示的url有保存，评论区域的图片url暂时没有采集（后期也可以添加进去），后期可能填入二进制文件下载模块。目前的工作流程这项工作优先级较为靠后。
你可以尝试自己添加然后提一个pull requests。

**Comment by betawen** [comment]
啥时候毕业，考虑点评吗👀
