### ISSUE TITLE
麻烦问问大佬，等待过一晚，也注册了新号，发现还是评论页被ban（可以爬取详情

### ISSUE THREAD

**Issue by EZ4BRUCE** [Sniper970119/dianping_spider#20]
也更改过那个时间，但是好像没什么用。。。

**Comment by EZ4BRUCE** [comment]
我发现，我从chrome下拿cookie换成edge拿cookie（后者会比前者多几个字段fspop=test; cy=4; cye=guangzhou; ）然后可以了

**Comment by Sniper970119** [comment]
这个我确实不清楚，后期你可以反复确定一下。如果属实希望您回来说明一下。
（我一开始写也没有这几个字段，后来一直都有。PS 我一直用的firefox）。

如果没有什么其他的问题，就给这个issue关了吧。

如果这个信息属实，我会在文档里指向该issue

**Comment by EZ4BRUCE** [comment]
好的

Yu ***@***.***> 于2021年6月6日周日 上午11:17写道：
