### ISSUE TITLE
关于cookie

### ISSUE THREAD

**Issue by GX17LuSunSky** [Sniper970119/dianping_spider#21]
大佬我想问一下那个大众点评浏览器上的cookie能够直接使用吗，我把cookie复制到我的headers中，好像还是不能够获取第二页以后的网页内容

**Comment by Sniper970119** [comment]
能。
第二页以后指的是大于等于2还是大于2。如果是大于等于那就是复制出错了

**Comment by GX17LuSunSky** [comment]
蟹蟹大佬，果然是我错了，之前是手打的，现在使用spilit分割就能够访问了
