### ISSUE TITLE
开发者你好，我运行报错如下，麻烦问一下这是哪里的问题啊？

### ISSUE THREAD

**Issue by TEAMO233** [Sniper970119/dianping_spider#27]
![image](https://user-images.githubusercontent.com/48355264/137058237-13805957-5cb4-4d40-8be2-8a20b0f3a1e2.png)

**Comment by Sniper970119** [comment]
你这个问题是你没有好好阅读文档造成的。详见：https://github.com/Sniper970119/dianping_spider/blob/master/docs/proxy.md

https://github.com/Sniper970119/dianping_spider/blob/master/README.md?plain=1#L114

另外请记住：

> 虽然我已经尽量编写详细的使用文档，即便如此：
    如果您是发现了bug或者有什么更好的提议，欢迎给我发邮件提issues、或PR，但是跟程序运行有关的所有问题请自行解决或查看这里。
    不接受小白提问，自行研究。文档比较完善，阅读完完整文档后如还有有疑问，提问时请展示你思考验证的过程。

**Comment by TEAMO233** [comment]
🙏
