### ISSUE TITLE
A系统中可能没有安装或启动MongoDB数据库

### ISSUE THREAD

**Issue by zihaom** [Sniper970119/dianping_spider#30]
A开发者你好，我跑main的时候报这个错. （WARNING: 系统中可能没有安装或启动MongoDB数据库，请先根据系统环境安装或启动MongoDB，再运行程序）
目前访问http://127.0.0.1:27017/会提示It looks like you are trying to access MongoDB over HTTP on the native driver port.
用的是anaconda prompt跑的，没有动过config.ini。mongoDB用的5.0。
能帮我想想是哪里出了问题吗？ 谢谢，我mongoDB不是很熟。。。

**Comment by Sniper970119** [comment]
config.ini里需要手动配置mongodb地址。详情查看config.ini中的注释
另外可以试试navicat，一个数据库可视化软件，用来可视化数据库中的内容。


如果该问题得到解决，请您关闭这个issue





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sniper970119/dianping_spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月6日(星期天) 中午12:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Sniper970119/dianping_spider] A系统中可能没有安装或启动MongoDB数据库 (Issue #30)





 
A开发者你好，我跑main的时候报这个错. （WARNING: 系统中可能没有安装或启动MongoDB数据库，请先根据系统环境安装或启动MongoDB，再运行程序）
 目前访问http://127.0.0.1:27017/会提示It looks like you are trying to access MongoDB over HTTP on the native driver port.
 用的是anaconda prompt跑的，没有动过config.ini。mongoDB用的5.0。
 能帮我想想是哪里出了问题吗？ 谢谢，我mongoDB不是很熟。。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zihaom** [comment]
谢啦，实在不好意思这么简单地东西麻烦你
