### ISSUE TITLE
关于tcv、uuid 的一些使用信息

### ISSUE THREAD

**Issue by qqizai** [Sniper970119/dianping_spider#31]
- [x] uuid，在不用 cookie 的 场合下使用的时候，可以直接随机生成；
- [x] 出验证码的情况下，原uuid+新ip不一定能过验证码，还是返回验证码；随机uuid+新的ip可以请求成功；
- [x] 但是,在有 cookie 场合 下随机 uuid 还没测试，因为封号限制太严格，没有进行测试；

- [ ] tcv 是否可以随机生成，还在测试中；

**Comment by Sniper970119** [comment]
感谢关注，
我也发现uuid并不是很重要。但是您第四个问题应该是不可以，这个我测试过程中还挺重要，但是uuid倒是确实无所谓。
对于验证码，我测试来看大部分情况手动跳过后都能通过风控。但是也不排除我测试的有些问题。


再次感谢关注，如果您愿意您可以更新代码提PR
再次感谢您的关注





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sniper970119/dianping_spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 下午5:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Sniper970119/dianping_spider] 关于tcv、uuid 的一些使用信息 (Issue #31)





  
 
 uuid，在不用 cookie 的 场合下使用的时候，可以直接随机生成；
 
 
 
 出验证码的情况下，原uuid+新ip不一定能过验证码，还是返回验证码；随机uuid+新的ip可以请求成功；
 
 
 
 但是,在有 cookie 场合 下随机 uuid 还没测试，因为封号限制太严格，没有进行测试；
 
 
 
 tcv 是否可以随机生成，还在测试中；
 
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qqizai** [comment]
好的，谢谢反馈哈。

刚刚去翻了一下js，tcv 等于：

`tcv = window.shop_config & window.shop_config.textCssVersion`

tcv 是服务器返回的，应该是对应字体 css 样式版本相关的，不能随机。

**Comment by Sniper970119** [comment]
哇 大佬翻了好多js哈哈哈，感谢大佬指点。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sniper970119/dianping_spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月10日(星期四) 下午3:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sniper970119/dianping_spider] 关于tcv、uuid 的一些使用信息 (Issue #31)





 
好的，谢谢反馈哈。
 
刚刚去翻了一下js，tcv 等于：
 
tcv = window.shop_config &amp; window.shop_config.textCssVersion
 
tcv 是服务器返回的，应该是对应字体 css 样式版本相关的，不能随机。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
