### ISSUE TITLE
处理验证码，按任意键回车后继续 https://verify.meituan.com

### ISSUE THREAD

**Issue by zihaom** [Sniper970119/dianping_spider#33]
A我复制这个链接到浏览器后滑动验证都在网页上报错：请求异常,拒绝操作。
试过chrome edge 和 IE，间隔24小时， 都是这个情况。
是不是跟我在国外有原因。。。

**Comment by Sniper970119** [comment]
根据我的经验来说是，我有的时候忘记关全局vpn也会这样。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sniper970119/dianping_spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月14日(星期一) 下午3:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Sniper970119/dianping_spider] 处理验证码，按任意键回车后继续 https://verify.meituan.com (Issue #33)





 
A我复制这个链接到浏览器后滑动验证都在网页上报错：请求异常,拒绝操作。
 试过chrome edge 和 IE，间隔24小时， 都是这个情况。
 是不是跟我在国外有原因。。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ding-001** [comment]
请问你解决了吗？我也是这个问题

**Comment by JagnDC** [comment]
> 请问你解决了吗？我也是这个问题

同样的问题，所有方法都试过了，都没法过验证

**Comment by zihaom** [comment]
得要想办法找国内的童鞋帮忙跑吧。。。这得看rp的嘿嘿嘿

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
