### ISSUE TITLE
A 关于处理验证码，按任意键回车后继续问题

### ISSUE THREAD

**Issue by JagnDC** [Sniper970119/dianping_spider#34]
使用了隧道代理，去掉了cookie，还是会出现验证码的情况，而且好像没法手动解决，可以麻烦作者帮忙看一下是什么问题吗？

[config]
use_cookie_pool = False
Cookie:
uuid : rth430b2-d52a-2550-a522-ebaebbf4ca16.164xxxxxxxx
tcv = 0x0xrqxxxx
user-agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
save_mode = mongo
mongo_path = mongodb://localhost
requests_times = 1,2;3,5;10,50
[detail]
keyword = 美食
location_id = 4
channel_id = 
search_url =
need_first = False
need_pages = 10
[proxy]
use_proxy = True
repeat_nub = 5
http_extract = False
key_extract = True
http_link = 
proxy_host = http-short.xxxxxx.com
proxy_port = 100xx
key_id = 8301678xxxxxxxxxxxx
key_key = yJDxxxxx

**Comment by Sniper970119** [comment]
我有说可以去掉cookie么



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JagnDC ***@***.***&gt;
发送时间: 2022年4月10日 04:32
收件人: Sniper970119/dianping_spider ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Sniper970119/dianping_spider] A 关于处理验证码，按任意键回车后继续问题 (Issue #34)





 
使用了隧道代理，去掉了cookie，还是会出现验证码的情况，而且好像没法手动解决，可以麻烦作者帮忙看一下是什么问题吗？
 
`
 [config]
 use_cookie_pool = False
 Cookie:
 uuid : rth430b2-d52a-2550-a522-ebaebbf4ca16.164xxxxxxxx
 
tcv，获取方法详见文档，使用加密接口时使用
 
tcv = 0x0xrqxxxx
 user-agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
 save_mode = mongo
 mongo_path = mongodb://localhost
 requests_times = 1,2;3,5;10,50
 [detail]
 keyword = 美食
 location_id = 4
 
频道号
 
channel_id =
 search_url =
 need_first = False
 need_pages = 10
 [proxy]
 use_proxy = True
 repeat_nub = 5
 http_extract = False
 key_extract = True
 http_link =
 proxy_host = http-short.xxxxxx.com
 proxy_port = 100xx
 key_id = 8301678xxxxxxxxxxxx
 key_key = yJDxxxxx
 
`

**Comment by JagnDC** [comment]
我大概明白了，谢谢
最后想请问一下，是应该使用登录之后的cookie还是未登录的cookie？
使用登录之后的cookie可以开始爬取，但是还是会跳验证码，这个是不能避免的吗？
