### ISSUE TITLE
使用代理报错

### ISSUE THREAD

**Issue by linyl1998** [Sniper970119/dianping_spider#35]
![image](https://user-images.githubusercontent.com/61406952/164876945-0e8397b2-ee97-40e0-993d-c4c7716e9c05.png)
您好，请问我不使用代理的时候店铺信息可以获得 评论获取直接被ban了 于是就想买代理来尝试 但是用代理后报错 
请问代理是这样设置的吗
![image](https://user-images.githubusercontent.com/61406952/164877571-d61d08dc-e44a-41b8-8b9d-e71875ba86a8.png)

**Comment by Sniper970119** [comment]
感觉不太对。这是两种不同的代理提取方式。具体区别与方法自行百度



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: linyl1998 ***@***.***&gt;
发送时间: 2022年4月23日 12:38
收件人: Sniper970119/dianping_spider ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Sniper970119/dianping_spider] 使用代理报错 (Issue #35)
