### ISSUE TITLE
推荐菜数据为空

### ISSUE THREAD

**Issue by pthtc** [Sniper970119/dianping_spider#37]
<img width="987" alt="image" src="https://user-images.githubusercontent.com/11351849/172042794-c3f6639d-45b0-499b-8354-19b3d0635702.png">

按照教程配置后，抓取顺利，数据准确，但是推荐菜字段为空，跪求大佬看看~

**Comment by Sniper970119** [comment]
detail字段为False&nbsp; 修改为True




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sniper970119/dianping_spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月5日(星期天) 下午4:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Sniper970119/dianping_spider] 推荐菜数据为空 (Issue #37)





 

 
按照教程配置后，抓取顺利，数据准确，但是推荐菜字段为空，跪求大佬看看~

**Comment by pthtc** [comment]
> detail字段为False&nbsp; 修改为True
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Sniper970119/dianping_spider" ***@***.***&gt;; 发送时间:&nbsp;2022年6月5日(星期天) 下午4:47 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[Sniper970119/dianping_spider] 推荐菜数据为空 (Issue #37) 按照教程配置后，抓取顺利，数据准确，但是推荐菜字段为空，跪求大佬看看~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

这里的detail是在哪个文件配置嘞？
config里只有搜索词之类的配置，require里看起来也没有提及推荐菜的配置。

**Comment by Sniper970119** [comment]
https://github.com/Sniper970119/dianping_spider#%E8%BF%90%E8%A1%8C%E7%A8%8B%E5%BA%8F
