### ISSUE TITLE
无评论的商家会报错中断

### ISSUE THREAD

**Issue by Euclid-Jie** [Sniper970119/dianping_spider#39]
首先非常感谢您这个项目的帮助！
我需要遍历某地区所有银行网点，以及其评论信息。部分银行无评论信息，程序会报错终止，我尝试修改`review.py`，将这部分的循环`reviews = html.select('.reviews-items')[0].select('.main-review')`，添加`try`结构。这样以来缺失不会报错终止，但是数据库中不会写入这些无评论的银行数据。
非常期待得到您的答复

**Comment by Sniper970119** [comment]
你好，给一个具体链接看一下吧，我这看如果只对那一句话加try，应该是可以正确保存其他非评论细节内容的

**Comment by Euclid-Jie** [comment]
> 你好，给一个具体链接看一下吧，我这看如果只对那一句话加try，应该是可以正确保存其他非评论细节内容的

比如这个银行https://www.dianping.com/shop/k9eAOr5aKpO17sgm

**Comment by Euclid-Jie** [comment]
> 你好，给一个具体链接看一下吧，我这看如果只对那一句话加try，应该是可以正确保存其他非评论细节内容的
感谢您，是我pycharm查看数据库只显示了前20条数据，让我误以为没有写入，非常感谢您的回复
