### ISSUE TITLE
什么时候上团购优惠券信息功能呢？

### ISSUE THREAD

**Issue by oceanicstar** [Sniper970119/dianping_spider#42]
如题。
        值此辞旧迎新之际，祝老板新年快乐，万事如意，工作顺利，在update上也能速战速决！<doge><doge><doge>

**Comment by Sniper970119** [comment]
感谢您的关注，也祝您新年快乐，身体健康。
相关的加解密方法已经全都有了，方法也已经抽出来（但是没实现，在[这里](https://github.com/Sniper970119/dianping_spider/blob/master/function/get_encryption_requests.py#L185)），可以参考其他[方法](https://github.com/Sniper970119/dianping_spider/blob/master/function/get_encryption_requests.py#L127)实现。 已经比较简单了。

我由于工作原因（利益相关），暂时不再会维护这个仓库。
