### ISSUE TITLE
处理验证码，但是打开链接之后滑动验证不通过：请求异常,拒绝操作

### ISSUE THREAD

**Issue by easpasta** [Sniper970119/dianping_spider#45]
A
大佬你好，运行之后显示“处理验证码，按任意键回车后继续”，打开后面跟着的链接能进入验证滑块界面，但是滑动之后就出现“请求异常,拒绝操作”。正常用浏览器打开网页是不会报错的。浏览器是新下载的，应该不存在需要清除cookie，也尝试了注释掉detail、review和search三个文件的加密（注释了获取加密文件、替换加密文件这两行，不知道注释对了没有），但是一样报错。我按了f12之后看到有个415错误，搜到一个解决办法是加一个contentType，但是我即不知道这到底有没有用，也不知道具体加在哪。

**Comment by Sniper970119** [comment]
contentType=json啥的那一串吗？那个不需要，一般服务器都不会对这个进行校验。

清除cookie和浏览器是不是新下载的没有关系，主要是清空一些服务器和本地记录的一些状态。

**Comment by easpasta** [comment]
我清除了cookie，重新登录，但是一运行就显示cookie失效或者被限制访问。注释掉解密之后能获取数据，但是爬到的评论有很多乱码。

**Comment by Sniper970119** [comment]
因为解密就是为了处理乱码的

**Comment by easpasta** [comment]
哦哦，这个我倒是看出来了，所以我后面没再注释掉了。现在的问题就是：清除cookie之后重新登录获取新cookie之后还是提示cookie失效或被限制访问。

**Comment by Sniper970119** [comment]
那就是解密的文件请求被ban了，人工多访问几个网页什么的，每一类页面都点一点，应该会有验证码
