### ISSUE TITLE
接口并发处理

### ISSUE THREAD

**Issue by Achernar0208** [Sniper970119/dianping_spider#48]
首先感谢作者的开源代码，对我有很大帮助~
我有个疑问：代码在获取酒店详细信息时已经解密接口，且接口请求不需要cookie，那么为什么不考虑使用多线程或者协程来进行接口请求呢？这样一方面可以加快速度，另一方面也节约了代理的成本（代理一般都支持多并发）。是因为有其他限制吗？

**Comment by Sniper970119** [comment]
其实所有的接口都支持并发，因为本质上都是高匿访问。
但是你获取id的途径是会发真实cookie到服务器的。因此并发打接口意味着你向服务器发送你的cookie的频率会增加。我认为有点得不偿失。

**Comment by Achernar0208** [comment]
> 其实所有的接口都支持并发，因为本质上都是高匿访问。 但是你获取id的途径是会发真实cookie到服务器的。因此并发打接口意味着你向服务器发送你的cookie的频率会增加。我认为有点得不偿失。

明白了，感谢！另外我发送了一份全国所有地区的location_id文件，希望对项目有帮助

**Comment by Sniper970119** [comment]
十分感谢！或许您可以提一下PR？更新到location中
