### ISSUE TITLE
不停更新cookie还是一直提示cookie过期，是怎么回事呀，登陆也没有要验证码的

### ISSUE THREAD

**Issue by Shawn1ee** [Sniper970119/dianping_spider#49]

**Comment by Shawn1ee** [comment]
另外怎么快速下载cookie呀，我每次都是一条一条复制，json下载的格式也不对。

**Comment by Sniper970119** [comment]
复制错了。chrome浏览器可以一键复制整条。

**Comment by yx-233** [comment]
这个cookie是直接从chrome浏览器复制过来就行了吗

**Comment by yunyun1234567** [comment]
我也有这个问题。过个几天或者用别人的cookie也只能爬十页的评论数据。我去年试的时候还是可以爬很多家完整的评论数据的。

**Comment by yunyun1234567** [comment]
A 我也有这个问题。属于这一种“cookie失效或者被限制访问”。过个几天或者用别人的cookie也只能爬十页的评论数据。我去年试的时候还是可以爬很多家完整的评论数据的。
