### ISSUE TITLE
cookie失效非常快，大佬有什么建议没？

### ISSUE THREAD

**Issue by rainbowshine521** [Sniper970119/dianping_spider#5]
WARNING: cookie失效或者被限制访问，更新cookie或登录大众点评滑动验证

我设置的：
# 累计请求多少次休息多少秒，从小到大排列。例：1,2;5,10 代表每请求1次休息2秒，每5次休息10秒。
requests_times = 1,5;3,20;10,80

**Comment by Sniper970119** [comment]
更新最新版，会暂停程序要求你手动解除验证码。
点评的反爬措施会不定时向你推送验证码，如果不处理验证码就会封cookie。

这个一定程度上会缓解无效cookie，但是并不能避免。

**Comment by rainbowshine521** [comment]
可否搞个代理池进来?

**Comment by Sniper970119** [comment]
带cookie加代理，你指定是嫌封的慢。
