### ISSUE TITLE
WARNING: cookie失效或者被限制访问，更新cookie或登录大众点评滑动验

### ISSUE THREAD

**Issue by trojanyao** [Sniper970119/dianping_spider#54]
A（已阅读 problems 文档以及其他所有文档）

### 配置文件
<img width="1187" alt="Xnip2023-07-18_10-35-57" src="https://github.com/Sniper970119/dianping_spider/assets/22811809/fe456c1b-f70c-431a-bd0e-166d5ea7c830">

### 运行结果
<img width="922" alt="Xnip2023-07-18_10-35-21" src="https://github.com/Sniper970119/dianping_spider/assets/22811809/8ef048a0-289f-4123-bbd6-70fd8cde8b70">

### 尝试过的方法
- 用自己账号的 Cookie、uuid 和 tcv（且多次重新登录刷新）
- 无痕模式用自己账号的 Cookie、uuid 和 tcv
- 用别人账号的 Cookie、uuid 和 tcv

均无效，应该不是账号被 ban 了。

### 类似问题
#49 
#45 
#43

**Comment by Sniper970119** [comment]
感谢关注。目前看接口在外网环境下确实已经失效，目前大众点评不存在完全高匿的接口，必须要带cookie发出去。之前可能是因为内网的拦截策略不一样一直没发现。
但是整体流程应该没发现大规模的变化。如果您测试还发现这个问题可以上传一下配置文件，晚些我在外网测试一下

**Comment by NiuJC** [comment]
一样的问题，更新过cookie之后仍然无法访问‘

**Comment by Sniper970119** [comment]
需要更新代码，在高匿接口中带cookie出去。具体原因
https://github.com/Sniper970119/dianping_spider/issues/54#issuecomment-1639580198
这里已经提到过，目前策略收紧，只有在内网环境才可以不带cookie访问。外网需要带cookie。
