### ISSUE TITLE
运行总是提示这个如何处理

### ISSUE THREAD

**Issue by beautifulxu** [Sniper970119/dianping_spider#56]
详情页请求被ban，程序继续运行

**Comment by beautifulxu** [comment]
<img width="1390" alt="image" src="https://github.com/Sniper970119/dianping_spider/assets/24916244/1358a1a8-c360-4aaa-91f0-69fa71050f0b">

**Comment by beautifulxu** [comment]
<img width="1289" alt="image" src="https://github.com/Sniper970119/dianping_spider/assets/24916244/46ad261f-e9e8-4f50-a2ea-77e7e7771d56">

**Comment by Sniper970119** [comment]
爬取间隔太快。
爬取分为搜索页和详情页还有评论页。这种情况就是部分页面因为访问太快限制访问，但是其他几种页面还可以访问
