### ISSUE TITLE
Search pag_nub

### ISSUE THREAD

**Issue by HSDyz** [Sniper970119/dianping_spider#57]
大佬，怎么增加一个缓冲区，有时候爬数据提示cookie失效，替换了也不行，只能结束重新爬，不想从头开始，想继续刚才的断点位置。

**Comment by Sniper970119** [comment]
一个简单的方式就是在配置里更改起始页。
这个问题我很久之前放到过Todo里，只不过后来被更高优的优化给顶替了hhh。你可以试着更改一下提一个pr。
就是在具体的 爬取/解析 加一个监测代码（比如try/catch），对于异常爬取写库，运行时优先从对应库中取数据。

**Comment by HSDyz** [comment]
感谢
