### ISSUE TITLE
搜索页请求被ban，程序终止

### ISSUE THREAD

**Issue by cyaduki** [Sniper970119/dianping_spider#61]
感谢开发者大佬！
提示如title，是我这边配置有什么问题吗，或者是因为海外IP？

**Comment by Sniper970119** [comment]
首先海外ip会有影响。
其次如果跑一会（而不是一开始就触发）触发这个警告，详见[文档](
https://github.com/Sniper970119/dianping_spider/blob/master/docs/problems.md#2-warning-%E8%AF%A6%E6%83%85%E9%A1%B5%E8%AF%B7%E6%B1%82%E8%A2%ABban)。

**Comment by cyaduki** [comment]
> 首先海外ip会有影响。 其次如果跑一会（而不是一开始就触发）触发这个警告，详见[文档](https://github.com/Sniper970119/dianping_spider/blob/master/docs/problems.md#2-warning-%E8%AF%A6%E6%83%85%E9%A1%B5%E8%AF%B7%E6%B1%82%E8%A2%ABban)。

感谢大佬回复！ 是一开始就触发了的，我尝试了下海外IP打开大众点评任何网页都会直接403所以应该是IP问题。
更改使用国内代理后提示和#54同样错误（刚跑就提示），尝试手动网页登录获取网页上cookie也没有改变，目前的话是只能想办法获取动态cookies了吗？

**Comment by Sniper970119** [comment]
1.动态cookie+动态ip可能才有增益。单动态cookie增益不大，还是会封ip。
2.更改国内代理后可能需要你先手动浏览一遍点评，可能会有一些前置验证码需要你处理。
3.程序无关：在打 #54 之前在#前加一个空格，会自动跳转到对应issue。
