### ISSUE TITLE
 cookie失效或者被限制访问，更新cookie或登录大众点评滑动验证

### ISSUE THREAD

**Issue by jy-98** [Sniper970119/dianping_spider#64]
![image](https://github.com/user-attachments/assets/f97f857a-fecd-4c55-bfb2-012fe6fb8260)
能帮忙看下什么问题吗   我这边大众点评的网站也登陆了

**Comment by rebootcat** [comment]
Bee...您的邮件已经收到啦

**Comment by jy-98** [comment]
![image](https://github.com/user-attachments/assets/543eca51-58f2-4c92-be3e-04ad7901d661)
抱歉我不是很理解。。

**Comment by Sniper970119** [comment]
替换正确的cookie
